name: QA Automation

on:
  push:
    branches: ["main"] # Runs pipeline on commits to main branch
  pull_request:
    branches: ["main"] # Also runs on PRs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # 3. Install dependencies and run tests
      - name: Install dependencies & run pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest --alluredir=reports/

      # 4. Install Allure CLI
      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.zip
          unzip allure-2.35.1.zip

      # 5. Generate Allure Report
      - name: Generate Allure Report
        run: ./allure-2.35.1/bin/allure generate reports/ -o reports_html --clean

      # 6. Upload Report as Artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: reports_html
